version: "3.9"

services:
  kivy-apk:
    build: 
      context: ./slaybot_apk
      dockerfile: Dockerfile
    container_name: kivy-builder
    user: "buildozer"
    
    volumes:
      # Code source : On monte uniquement le sous-dossier
      - ./slaybot_apk:/home/buildozer/app
      
      # SORTIES : On utilise le point "." pour dire "ici, à la racine"
      # On force le montage DIRECTEMENT sur les dossiers de sortie du conteneur
      - ./bin:/home/buildozer/app/bin
      - ./.buildozer:/home/buildozer/app/.buildozer
      
      # Volumes nommés (cachés par Docker pour le SDK/NDK)
      - buildozer-cache:/home/buildozer/.buildozer
      - gradle-cache:/home/buildozer/.gradle
      
    stdin_open: true
    tty: true
    working_dir: /home/buildozer/app
    command: buildozer android debug

volumes:
  buildozer-cache:
  gradle-cache: