version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres_restaurant
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: ./restaurant_site
    container_name: restaurant_app
    restart: unless-stopped
    command: python app.py
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./restaurant_site:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      POSTGRES_HOST: db
      HOTSPOT_WS_URL: ${HOTSPOT_WS_URL}
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres_data: